// Generated by CoffeeScript 1.10.0
var QRCode, makeQR;

QRCode = require('davidshimjs-qrcodejs');

makeQR = function(className, content, dimension) {
  var element;
  element = document.querySelector("." + className);
  dimension = 700;
  return new QRCode(element, {
    text: content,
    width: dimension,
    height: dimension,
    correctLevel: QRCode.CorrectLevel.H
  });
};

module.exports = makeQR;
