// Generated by CoffeeScript 1.10.0
var addrElem, adress, bitcore, keyElem, makeQR, privateKey;

makeQR = require('./make-qr');

bitcore = require('bitcore-lib');

privateKey = new bitcore.PrivateKey;

adress = privateKey.toAddress();

makeQR("qr_private_key", privateKey.toWIF());

makeQR("qr_address", adress.toString());

keyElem = document.querySelector(".private_key_label");

addrElem = document.querySelector(".address_label");

keyElem.innerHTML = privateKey.toWIF();

addrElem.innerHTML = adress.toString();
