// Generated by CoffeeScript 1.10.0
var QRCode, bitcore, element, qrcode;

QRCode = require('davidshimjs-qrcodejs');

bitcore = require('bitcore-lib');

element = document.querySelector(".qr_address");

qrcode = new QRCode(element, {
  text: "http://jindo.dev.naver.com/collie",
  width: 128,
  height: 128
});
