// Generated by CoffeeScript 1.10.0
var adress, bitcore, makeQR, privateKey;

makeQR = require('./make-qr');

bitcore = require('bitcore-lib');

privateKey = new bitcore.PrivateKey;

adress = privateKey.toAddress();

makeQR("qr_private_key", privateKey.toWIF());

makeQR("qr_address", privateKey.toWIF());
